Transform
Spatio-Temporal-Lab/start-db-achive pull request #261
Opened 2022-06-25 10:40 UTC by TYXXXXXXX

2022-06-25 11:22 UTC, IrisLoveLeo reviewed
很赞了，进步很大。

2022-06-25 11:22 UTC, IrisLoveLeo commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +    )
轨迹路段路网 geometry这些的测试，能否也加上

2022-06-25 16:07 UTC, l1519316637 requested changes

2022-06-25 16:07 UTC, l1519316637 commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/CoordTransformFunction.java
> +        return (GeometryCollection) transformer.geometryTransform(geometryCollection);
return transformer.geometryCollectionTransform(geometryCollection);
调用这个函数
其他的六个关于geometryCollection的udf都要改一下

2022-06-25 16:07 UTC, l1519316637 commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/CoordTransformFunction.java
> +        return (GeometryCollection) transformer.geometryTransform(geometryCollection);
return transformer.geometryCollectionTransform(geometryCollection);

2022-06-25 16:07 UTC, l1519316637 commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/CoordTransformFunction.java
> +        return (GeometryCollection) transformer.geometryTransform(geometryCollection);
return transformer.geometryCollectionTransform(geometryCollection);

2022-06-25 16:07 UTC, l1519316637 commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/CoordTransformFunction.java
> +        return (GeometryCollection) transformer.geometryTransform(geometryCollection);
return transformer.geometryCollectionTransform(geometryCollection);

2022-06-25 16:07 UTC, l1519316637 commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/CoordTransformFunction.java
> +        return (GeometryCollection) transformer.geometryTransform(geometryCollection);
return transformer.geometryCollectionTransform(geometryCollection);

2022-06-25 16:07 UTC, l1519316637 commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/CoordTransformFunction.java
> +        return (GeometryCollection) transformer.geometryTransform(geometryCollection);
return transformer.geometryCollectionTransform(geometryCollection);

2022-06-29 08:32 UTC, l1519316637 approved these changes, later dismissed

2022-06-29 08:56 UTC, l1519316637 reviewed
合并之后拉取新代码

2022-06-29 09:43 UTC, IrisLoveLeo reviewed
@l1519316637 

李政，这个pr你也把关一下吧。

2022-06-29 09:43 UTC, IrisLoveLeo commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/CoordTransformFunction.java
> +        AbstractCoordTransformer transformer = new WGS84ToBD09Transformer();
所有gcj02这里都搞错了
你其他的都检查一下

2022-06-29 09:43 UTC, IrisLoveLeo commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/CoordTransformFunction.java
> +        AbstractCoordTransformer transformer = new WGS84ToBD09Transformer();
这里也错了

2022-06-29 09:43 UTC, IrisLoveLeo commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/coordtransform/BD09ToGCJ02Transformer.java
> +        return CoordTransformUtils.gcj02Tobd09(lng, lat);
这里调用的方法不对啊，要跟类一致

2022-06-29 09:43 UTC, IrisLoveLeo commented on start-db-calcite/src/main/java/org/urbcomp/start/db/function/coordtransform/GCJ02ToWGS84Transformer.java
> +        return CoordTransformUtils.gcj02Tobd09(lng, lat);
这里完全是乱的

2022-06-29 09:50 UTC, LIZHZZ reviewed
好的老师

2022-06-30 07:02 UTC, IrisLoveLeo commented
@l1519316637 李政，这个pr你帮忙看一下

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +    val resultSet = statement.executeQuery("select st_BD09ToGCJ02(st_makePoint(1, 2))")
这个错了应该是st_WGS84ToGCJ02

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      "select st_BD09ToGCJ02(st_lineStringFromWKT('LINESTRING(0 0,1 1,1 2)'))"
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      "select st_BD09ToGCJ02(st_polygonFromWKT('POLYGON((1 1,5 1,5 5,1 5,1 1),(2 2,2 3,3 3,3 2,2 2))'))"
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      "select st_BD09ToGCJ02(st_mLineStringFromWKT('MULTILINESTRING((3 4,1 5,2 5),(-5 -8,-10 -8,-15 -4))'))"
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      "select st_BD09ToGCJ02(st_mPolygonFromWKT('MULTIPOLYGON(((1 1,5 1,5 5,1 5,1 1),(2 2,2 3,3 3,3 2,2 2))," +
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      statement.executeQuery("select st_BD09ToGCJ02(st_mPointFromWKT('MULTIPOINT((1 2),(3 4))'))")
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +    val resultSet = statement.executeQuery("select st_BD09ToGCJ02(st_makePoint(1, 2))")
这个st_GCJ02ToWGS84

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      "select st_BD09ToGCJ02(st_lineStringFromWKT('LINESTRING(0 0,1 1,1 2)'))"
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      "select st_BD09ToGCJ02(st_polygonFromWKT('POLYGON((1 1,5 1,5 5,1 5,1 1),(2 2,2 3,3 3,3 2,2 2))'))"
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      statement.executeQuery("select st_BD09ToGCJ02(st_mPointFromWKT('MULTIPOINT((1 2),(3 4))'))")
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      "select st_BD09ToGCJ02(st_mLineStringFromWKT('MULTILINESTRING((3 4,1 5,2 5),(-5 -8,-10 -8,-15 -4))'))"
同上

2022-07-01 03:16 UTC, l1519316637 commented on start-db-core/src/test/scala/org/urbcomp/start/db/CoordTransformFunctionTest.scala
> +      "select st_BD09ToGCJ02(st_mPolygonFromWKT('MULTIPOLYGON(((1 1,5 1,5 5,1 5,1 1),(2 2,2 3,3 3,3 2,2 2))," +
同上

2022-07-04 02:05 UTC, IrisLoveLeo approved these changes

2022-07-04 02:05 UTC, merged