Drop table function
Spatio-Temporal-Lab/start-db-achive pull request #279
Opened 2022-06-29 05:16 UTC by cquhx

2022-06-29 07:20 UTC, IrisLoveLeo commented
之后分支命名按照“姓名/功能”命名哈，比如：hexiang/droptable

2022-06-29 07:38 UTC, IrisLoveLeo requested changes

2022-06-29 07:38 UTC, IrisLoveLeo commented on start-db-core/src/main/scala/org/urbcomp/start/db/executor/DropTableExecutor.scala
> +    val (userName, dbName, tableName) = (targetTable(0), targetTable(1), targetTable(2))
参考insertExecutor的方式，因为有可能不同的语法，比如：drop table dbName.tableName或者直接drop table tableName

2022-06-29 07:38 UTC, IrisLoveLeo commented on start-db-core/src/main/scala/org/urbcomp/start/db/executor/DropTableExecutor.scala
> +    val schemaName = MetadataUtil.makeSchemaName(tableId)
这一行后面的可以删除hbase表的代码可以删除了，我们采用的是懒删除的形式

2022-06-29 07:38 UTC, IrisLoveLeo commented on start-db-core/src/main/scala/org/urbcomp/start/db/executor/DropTableExecutor.scala
> +    val schemaName = MetadataUtil.makeSchemaName(tableId)
会有一个进程在后面删除hbase的表。

2022-06-29 07:38 UTC, IrisLoveLeo commented on start-db-core/src/main/scala/org/urbcomp/start/db/executor/DropTableExecutor.scala
> +      tableAccessor.deleteById(tableId, false)
然后这里的false可以改成true

2022-06-29 07:38 UTC, IrisLoveLeo commented on start-db-core/src/main/scala/org/urbcomp/start/db/executor/DropTableExecutor.scala
> +      MetadataUtil.combineUserDbTableKey(userName, dbName, tableName)
这里挺好的

2022-06-29 07:38 UTC, IrisLoveLeo commented on start-db-core/src/test/scala/org/urbcomp/start/db/executor/TableExecutorTest.scala
> +    }
你再测试一下drop table if exist语句

2022-06-29 11:00 UTC, cquhx commented on start-db-core/src/main/scala/org/urbcomp/start/db/executor/DropTableExecutor.scala
> +    val (userName, dbName, tableName) = (targetTable(0), targetTable(1), targetTable(2))
老师这儿传进来的参数类型就是user.db.table的形式，跟create不同，是要改传进来的参数吗

2022-06-29 11:04 UTC, IrisLoveLeo commented on start-db-core/src/main/scala/org/urbcomp/start/db/executor/DropTableExecutor.scala
> +    val (userName, dbName, tableName) = (targetTable(0), targetTable(1), targetTable(2))
对的，你看看create是怎么传的，这里可能要修改语法文件和解析那块。你可以跟博鸿 @bee-corn  商量一下

2022-06-30 09:49 UTC, cquhx commented on start-db-core/src/main/scala/org/urbcomp/start/db/executor/DropTableExecutor.scala
> +      tableAccessor.deleteById(tableId, true)
那前面的select操作和fieldAccessor是都要改为false吗

2022-07-02 01:55 UTC, IrisLoveLeo approved these changes

2022-07-02 01:59 UTC, merged